### PR TITLE
Added french translations

### PR DESCRIPTION
**Pull request by jorys-paulin**
Hello everyone!

This pull request translates the strings for French in `resources/locale.json`.

I made sure to reference the original translations to make sure the Peacock strings are consistent with the rest of the game. I've built the locale packages locally to test them directly in-game and make sure everything's correct. As asked in the README, I've made sure not to include them in this PR.

PS: While testing, I actually found an issue with The sleazeball Situation, where there is a missing/wrong translation for level 1. I'm planning to make another PR to fix it along with other small issues I've noticed on other Peacock escalations.

### CODE REVIEW

**Review by AnthonyFuller — APPROVED** [review]
LGTM from a technical standpoint, await @alex73630.

> PS: While testing, I actually found an issue with The sleazeball Situation, where there is a missing/wrong translation for level 1. I'm planning to make another PR to fix it along with other small issues I've noticed on other Peacock escalations.

You can just push to the branch on you have, no need for a new PR.

**Comment by jorys-paulin** [comment]
> You can just push to the branch on you have, no need for a new PR.
I was going to do that first, but then I hit into some problems with one of the escalations and didn't want to delay the translation going through.

**Review by alex73630 — APPROVED** [review]
Translations seems correct to me, approved!

**Comment by jorys-paulin** [comment]
Hello! Seems like the locale packages didn't build correctly, despite trying three times, and now they're out of date with `locale.json`, should I open a pull request to update them while you fix whatever's wrong with the CI script?

**Comment by AnthonyFuller** [comment]
No. They will be fixed soon. It wouldn't matter anyway as they wouldn't be in a release. You'd only get the new translations if you updated them locally yourself, or are using the SMF mod (this is if the workflow ran successfully).

**Pull request merged**
