### PR TITLE
feat(menu): add escalation tile to H2/3 dashboard

### PR DESCRIPTION
**Pull request by AnthonyFuller**
This PR adds an escalations tile to the H2/3 dashboard, replacing the 4 featured Peacock escalations.

This tile just opens the enhanced "ContractAttack" hit category.
image

Also adds an elusive targets tile to the H2 dashboard, which functions the same as Career -> Elusive Targets (just fills it out)
image

This PR also adds some category names to certain logs, as I kept getting annoyed with the "unknown".

_Currently marked as a draft until the tile has been fixed_

### CODE REVIEW

**Comment by AnthonyFuller** [comment]
I have just pushed a working tile for the H3 dash for escalations.

It is ~~a bit~~ hacky as we hijack the arcade page for it to work. The old method does not work due to some menu limitation we've hit. This method is compatible with (a future version) of Heritage UI.

**Comment by AnthonyFuller** [comment]
Just pushed the page and tile for H2.

It is an unbelieveably hacky method.

**Comment by grappigegovert** [comment]
> Just pushed the page and tile for H2.
> 
> It is an unbelieveably hacky method.

... Wow

Nice job getting it to work tho!

**Comment by AnthonyFuller** [comment]
Yep, thanks. Had to push the whole `gamemodesniper_content.json` template instead of the 6-ish line `gamemodesniper_page.json` which wasn't getting retrieved from the servers (likely due to it being used the menuresources brick).

I was already hijacking the arcade page, which was fine as it's a short template.

This all adds onto `$arraygroupby` crashing with the `order` property in H2, so I have to push Peacock escalations _first_ and then the rest.

**Comment by AnthonyFuller** [comment]
This has been ready to merge since the last commit has been made.

**Comment by AnthonyFuller** [comment]
@RDIL this is ready to be merged, could it get your review please?

**Review by RDIL — APPROVED** [review]

**Pull request merged**
