### PR TITLE
Revert "Revert "Revert "Revert "Revert "Revert "Revert""""""

### PR DESCRIPTION
**Pull request by atampy25**
As requested by a member of the patcher team.

Included commits:
[Revert](https://github.com/thepeacockproject/Peacock/commit/9e13bf252aa34f8603182d0dbd79a51bf01f3804)
[Revert "Revert"](https://github.com/thepeacockproject/Peacock/commit/1eec52ccb4fbb9a658893cd39011df80a528e377) 
[Revert "Revert "Revert""](https://github.com/thepeacockproject/Peacock/commit/4922a3cb85da55c7837bf12040ce509a0e815d3a) 
[Revert "Revert"](https://github.com/thepeacockproject/Peacock/commit/559f71c06a0f072cbfd0d2d1043228bdf806c279) 
[Revert "Revert "Revert""](https://github.com/thepeacockproject/Peacock/commit/729db90985dc4298eb26b590e4389f5fa118909b) 
[Revert "Revert "Revert "Revert"""](https://github.com/thepeacockproject/Peacock/commit/1154b21bb25f7464f6e08e3d08575b471ecb1293) 
[Revert "Revert "Revert""](https://github.com/thepeacockproject/Peacock/commit/965dbbb2f1fdc710c80b51a69d369225968827b7) 
[Revert "Revert "Revert "Revert"""](https://github.com/thepeacockproject/Peacock/commit/71a8b7ddbd930a5bd9bba8410b9783d02074e48d) 
[Revert "Revert "Revert "Revert "Revert""""](https://github.com/thepeacockproject/Peacock/commit/4987557b58a0e77d41e1f8e130ccb4e40f3fb706) 
[Revert "Revert "Revert "Revert "Revert "Revert"""""](https://github.com/thepeacockproject/Peacock/commit/e06549c92a363bde08933c4cebbba123daf571c3) 
[Revert "Revert "Revert""](https://github.com/thepeacockproject/Peacock/commit/535047e82cfe9e6e589f4bed7b87038a01375af5) 
[Revert "Revert "Revert "Revert"""](https://github.com/thepeacockproject/Peacock/commit/3240bac8ec1e2f584407bb53a41f43c67725aba2) 
[Squashed commit of the following:](https://github.com/thepeacockproject/Peacock/commit/764036aedfde4369bb469b05cb796854f4e13dac) 
[Revert "Squashed commit of the following:"](https://github.com/thepeacockproject/Peacock/commit/db88863466e97e8390d9bac07cb7f4ce51d3c540) 
[Revert "Revert "Revert "Revert "Revert""""](https://github.com/thepeacockproject/Peacock/commit/18bd6bec99d7073db18d5b1e882ae33fdbfd0717) 
[Revert "Revert "Revert "Revert "Revert "Revert"""""](https://github.com/thepeacockproject/Peacock/commit/128599e6dc318094318613dcf44b45a8b710b136) 
[Merge branch 'Revert-Revert' into v5](https://github.com/thepeacockproject/Peacock/commit/dafc1e20687be6f930f193d692117720a444a892)
[Revert "Revert "Revert "Revert "Revert "Revert "Revert""""""](https://github.com/thepeacockproject/Peacock/commit/7412cd08e1dc2cd2bd6c26434a4abea410df5daf)

### CODE REVIEW

**Comment by atampy25** [comment]
What in the GODDAMN do you mean linting failing? I put my HEART and SOUL into this code and to see it DISPARAGED in such an UNFOUNDED way is SHAMEFUL and IMMORAL

**Comment by atampy25** [comment]
Oh my GOD this PR is ID 47! I'm so honoured to be the recipient of such an AMAZING GIFT!

Thank you God 🙏🙏🙏🙏🙏🙏🙏🙏 and Jesus 👶 and Reece Dunham for this INCREDIBLE opportunity!

**Review by musicalmushr00m — APPROVED** [review]
I’m here all weekend - come on ya fuckin punk ass swimmer 🙄 I’ll be waiting on ya - I’ll be waiting on your punk ass - wait matter of fact give me your address I’ll come to wherever you are and give you a chance to make good on your promises since I know you won’t actually come here me Navy SEAL lol what BUDS class were you in bitch? See you’re talking to an Army Ranger - RSC 13-2 - I’ve ACTUALLY been on clandestine missions - I’ve ACTUALLY been in gunfights - and on the 1% chance that you’re ACTUALLY a buds graduate I’ll tell you RQRF in the korangal - we were saving baby seals on a daily basis because they have no fucking idea what to do when bullets start flying the other direction - so no - I’m not worried about you - the USMC is still using gulf war hand me downs so you’re saying your equipment is dated and sporting extensive wear and tear? Annnndddd no need to involve your top secret lies I mean spies whoops - cuzzzzz I just told you and the internet where I live - you can come here or give me your address and I’ll come there - either way 😊

**Comment by atampy25** [comment]
LGTM

**Pull request closed without merging**
