### PR TITLE
Fixed drops from not showing on their respective challenges in the menu

### LINKED ISSUE #171: Challenges not showing their drops in the menus
Only XP is shown.

### PR DESCRIPTION
**Pull request by LennardF1989**
Fixes #171.

### CODE REVIEW

**Comment by LennardF1989** [comment]
Wow, this ESLint points out a weird one. The game actually works with this... Will look into what kind of magic is happening here.

**Review by AnthonyFuller — CHANGES_REQUESTED** [review]
@RDIL wants to rejig what we store regarding drops, that probably wants to be addressed or considered before merging this. (I'm surprised this slipped through)

**Comment by LennardF1989** [comment]
Wow, not sure how this happened. But when logging the supposed string array, it's actually a list of Unlockable objects. SavedChallenge is not the right type here.

**Comment by RDIL** [comment]
yeah we were supposed to store strings but somewhere in the pipeline that just didn't happen 🤷

**Comment by LennardF1989** [comment]
> yeah we were supposed to store strings but somewhere in the pipeline that just didn't happen 🤷

Fixed it proper now, testing. Will push in a moment.

**Review by RDIL — APPROVED** [review]

**Review by AnthonyFuller — APPROVED** [review]
LGTM

**Pull request merged**
