### PR TITLE
Add Elusive Target challenges on H3

### PR DESCRIPTION
**Pull request by moonysolari**
- Added contract-, location-, and global-wide Elusive Target challenges on H3. The challenges are from the following sources, with decreasing priority:
    - Retrieved from H3 official.
    - Adapted from H3 official "Year 2" versions of the elusive target.
    - Generated following the general template for Elusive Target challenges.
- Added a flag to toggle saving and restarting in ET sessions. You cannot complete challenges when saving is enabled, and vice versa.
- Updated The Angel of Death with VR blocks because I forgot last time.
- Added the script I used to extract ET challenges. It is currently specialized for H3 but has potential to be modified to work for more game versions. It is not optimized and does not have to be added to the repo, but it is helpful to whoever that wishes to add ET challenges to other game versions.

### CODE REVIEW

**Comment by AnthonyFuller** [comment]
We could allow restarting on elusive missions by editing a menu json.

**Comment by moonysolari** [comment]
I don't know how to do that.

**Comment by AnthonyFuller** [comment]
Is it okay if I push some changes to this branch? It will likely need a good amount of testing before final merge though.

**Comment by moonysolari** [comment]
Sure.

**Review by AnthonyFuller — APPROVED** [review]

**Comment by AnthonyFuller** [comment]
Ready to be merged, for H2/3 elusives won't be split into "Season X" categories until #63 is merged.

Await review from @RDIL more to make sure he's okay with what I've done in menu data.

**Review by RDIL — APPROVED** [review]

**Pull request merged**
