### PR TITLE
Get started on adding more playstyles

### PR DESCRIPTION
**Pull request by thecatontheceiling**
## Scope

Added new "Virtuoso Assassin" playstyle to get started on finally implementing more of them.
God damn most of the playstyles are annoying to figure out.

## Checklist

-   [x] I have run Prettier to reformat any changed files
-   [ ] I have verified my changes work

### CODE REVIEW

**Comment by thecatontheceiling** [comment]
This obviously needs fixing, i only had 2 minutes to write this 

Why even make this pull request then? good question

**Comment by thecatontheceiling** [comment]
will reopen when this PR gets in a state where it makes sense to merge

**Comment by thecatontheceiling** [comment]
I'm deleting the branch because it's very evident that there's basically 0 source of reliable info on how to get specific playstyles and it is extremely tedious to try to manually figure it out, it's a shame but I honestly think adding more is unfeasible and pointless if we get it very wrong

**Comment by RDIL** [comment]
Yeah, we've wanted to add more but it's tough without seeing the criteria.

**Pull request closed without merging**
