### PR TITLE
feat: season of drop challenges

### PR DESCRIPTION
**Pull request by suanjiansalt**
## Scope

- [x] Adding Fuel to the Fire
- [x] True Fan

## Test Plan

The challenges complete in game successfully

## Checklist

-   [x] I have run Prettier to reformat any changed files
-   [ ] I have verified my changes work

### CODE REVIEW

**Review by RDIL — APPROVED** [review]
Can be merged once a test plan is added

**Comment by suanjiansalt** [comment]
I'm just not sure how to 'plan' a test for this... of all time.

**Comment by suanjiansalt** [comment]
I'm just not sure how to 'plan' a test for this... of all time.

**Comment by RDIL** [comment]
In this case, a reasonable test plan would just be playing through both challenges to make sure they complete successfully

**Pull request merged**
