### PR TITLE
add contract mode in Romania and freeform training

### PR DESCRIPTION
**Pull request by WINNODD**
minor fixs for the tile/background image in snow festival/freeform training

### CODE REVIEW

**Review by RDIL — CHANGES_REQUESTED** [review]
Freeform training sounds fine, but Romania is not a map suitable for contracts.

**Comment by WINNODD** [comment]
I'm aware Romania is no common sandbox like other locations but yet it has every other essential element for contract mode. The reason I made this is to give people a chance to explore this map more than get in and kill the constant.
Just saying we don't have be as thoughtful as IO on such matter. In the end it's just peacock exclusive content.

**Comment by RDIL** [comment]
I understand your reasoning on the matter, but I think this is just not really something we want to have as a first-class feature.  A plugin can do this, and would probably be a better use of the API.

**Comment by RDIL** [comment]
The issue is that the scene file is not designed to support contracts.  It's already very very coupled to the main mission.

**Comment by RDIL** [comment]
Closing due to lack of activity.  Feel free to open a new PR if you are interested in pushing this forward.

**Pull request closed without merging**
