### PR TITLE
Add descriptions to Peacock escalations

### PR DESCRIPTION
**Pull request by jorys-paulin**
Hello everyone!

This pull request adds descriptions to every Peacock escalation, translated in all languages.

This actually fixes a bug with the "missing content" popup, where Peacock escalations don't show up properly.

For official escalations, players who don't own the required entitlement will get a popup that shows the content they're trying to access (including its description), the required content, and links to the relevant store:

HITMAN3_2023-09-11_20-41-32

However, for Peacock escalations this popup is broken, because their contract files are missing a `Description` field:

HITMAN3_2023-09-11_20-41-15

Adding descriptions fixes this issue, and now the popup looks as expected (and in user's language too!):

HITMAN3_2023-09-11_20-42-51

I've made sure the translations are correct and consistent with the game for French and German. Other languages were manually translated using the game's other translations and Google Translate, so I can't guarantee they are 100% accurate (Chinese for example), so a little checkup by the translators wouldn't hurt.

### CODE REVIEW

**Review by moonysolari — CHANGES_REQUESTED** [review]
Please only add translations for languages you are proficient in, and do not use AI translation tools to do the translations.

**Comment by jorys-paulin** [comment]
> Please only add translations for languages you are proficient in, and do not use AI translation tools to do the translations.

Should I just leave then untranslated in English then? That's going to look weird. Also, I don't think Google Translate is an "AI translation tool".

**Comment by moonysolari** [comment]
Yeah, just leave them in english.

**Comment by jorys-paulin** [comment]
I've un-translated them, since I've basically copy-pasted and checked them they're probably fine, but feel free to reach out to the translators later!

**Review by AnthonyFuller — CHANGES_REQUESTED** [review]
This PR is unnecessarily large. The descriptions are the same per escalation, so they should be `UI_PEACOCK_ESCALATION_<LOCATION>_DESC` e.g. `UI_PEACOCK_ESCALATION_PARIS_DESC`.

**Review by moonysolari — APPROVED** [review]

**Comment by jorys-paulin** [comment]
I've updated the descriptions to generic ones, they will now be "Peacock escalation in (Destination)". I've translated those in French and German, other languages fall back on English.

HITMAN3_2023-09-18_13-52-34
HITMAN3_2023-09-18_13-52-57

**Comment by suanjiansalt** [comment]
As we've gone this far... how about adding descriptions to all destinations as we may have further escalations? @jorys-paulin

**Review by AnthonyFuller — APPROVED** [review]

**Pull request merged**
