### PR TITLE
Add h1 escalations

### PR DESCRIPTION
**Pull request by Small-cart**
Add AMARYLLIS
image
image

### CODE REVIEW

**Comment by AnthonyFuller** [comment]
This most likely won't be merged, see #35.

It also isn't an actual escalation since you're missing images.

**Comment by Small-cart** [comment]
> This most likely won't be merged, see #35.
> 
> It also isn't an actual escalation since you're missing images.

**Comment by Small-cart** [comment]
can i make a image by myself?

**Comment by AnthonyFuller** [comment]
> Beside,it has 10 levels plugin is not support.

Plugins do have support for more than 5 levels from what I remember, you can add a single level escalation if you wanted.

Making the images yourself isn't the issue, you clearly did not read the other PR I referenced.

**Comment by Small-cart** [comment]
> > Beside,it has 10 levels plugin is not support.
> 
> Plugins do have support for more than 5 levels from what I remember, you can add a single level escalation if you wanted.


image
The plugins max support 9 levels

**Comment by AnthonyFuller** [comment]
They do support 10, as I have added a 10 level escalation before.

This isn't being added because of:
(a) The overhead of 10 contracts is quite large for an unreleased, unfinished, hellish escalation.
(b) RDIL has said that he wouldn't mind adding the escalations that actually got "released" in Hitman 3.

For that reason, I am closing this. Make it a plugin.

**Pull request closed without merging**
