### PR TITLE
Add Stingray & Opulent debriefings to the campaign menu

### PR DESCRIPTION
**Pull request by thecatontheceiling**
## Scope

Added the cutscenes to the campaign list so they show up in-game without having to play through the entire mission everytime you need to access it

## Test Plan

I have not verified if these changes work or not. I made this PR using my shitty Samsung phone which probably cannot emulate WoA.

The only thing missing afaik is the tile images:
```
images/cinematics/tiles_s2/cinematic9.jpg
images/cinematics/tiles_s2/cinematic10.jpg
```
They can be made and added to ImagePack although I'm not sure if that will work or not immediately.

[Dribbleondo made images that could be used](https://discord.com/channels/555224628251852811/555224758837444632/1273265607974060116)

[Relevant discord conversation](https://discord.com/channels/555224628251852811/555224758837444632/1273226359879241769)

## Checklist

-   [x] I have run Prettier to reformat any changed files
-   [ ] I have verified my changes work

### CODE REVIEW

**Comment by infradragon** [comment]
based

**Comment by suanjiansalt** [comment]
my question is, why does it have to be a feature of Peacock

**Comment by thecatontheceiling** [comment]
For consistency's sake I think these cutscenes should be in the Season 2 campaign among the missions they're for for easy access. 

They only get played after the mission is completed and they can't be accessed from the Season 2 campaign section like every other debriefing.

I don't really see why not

**Comment by dribbleondo** [comment]
> For the sake of consistency I think these cutscenes should be easily accessable in the Season 2 campaign among the missions they're for, for easy access.
> 
> They only get played after the missions are completed and they can't be accessed from the menu like every other debriefing which makes it a weird inconsistency.
> 
> I don't really see why not

Seconded. It's a weird choice to keep these only viewable after you play a level.

**Comment by Watchman3001** [comment]
Agree. Definitely wouldn't hurt to have those debriefing videos available without having to play through the mission again, or go on YouTube

**Comment by suanjiansalt** [comment]
In any case it's not a must option in Peacock. Being an attachment plugin of a mod could be more suitable.

**Comment by RDIL** [comment]
Feels like a reasonable thing to have in core. It’s not new content, just a button to access existing content.

**Comment by thecatontheceiling** [comment]
> Feels like a reasonable thing to have in core. It’s not new content, just a button to access existing content.

This concept of adding buttons to access existing content isn't very new to peacock in the first place
https://thepeacockproject.org/wiki/features/elusive-targets

**Comment by RDIL** [comment]
Willing to merge this, please PR in the images to the image pack. No more then 200kb per image, must be jpg.

**Review by RDIL — APPROVED** [review]

**Pull request merged**
