### PR TITLE
Another escalation qol fix batch

### PR DESCRIPTION
**Pull request by suanjiansalt**
- Fix the empty objective in notebook (F1 list page) in The Jeffrey Consolation, which is an additional fix to PR #139 .
- Remove unimportant entrances in The dez Dichotomy.
- Swap objectives to make the complication in _The Personage - Level 1_ have a pop away animation.

### CODE REVIEW

**Comment by RDIL** [comment]
Looks like this causes the tests to fail

**Comment by suanjiansalt** [comment]
> Looks like this causes the tests to fail

Is it necessary to change the format like

```json5
{
    "Targets": [
        "abc"
    ]
}
```

into:

```json5
{
    "Targets": ["abc"]
}
```

to pass the test? If so, is there a way to substitute normal Prettier plugin with this format type?

**Comment by grappigegovert** [comment]
Normal prettier should already format it on a single line.
If you have the entire repo cloned you can run `yarn prettier`, to format everything, but judging by the fact that you're uploading this through the web ui, you might not have.
What are you using currently to edit/format the files?

**Comment by suanjiansalt** [comment]
> What are you using currently to edit/format the files?

I edited on VSCode with this expansion installed: 
image

But I prefer to paste lines to github web to commit because I don't get familiar to the steps you commit in VSCode.

**Comment by grappigegovert** [comment]
If you press ctrl+shift+p to open vscode's command palette, you can do 'Format Document With ...' and then select Prettier.
It's not selected by default for some reason, I'll push a fix for that.

**Comment by grappigegovert** [comment]
You closed the PR?

**Comment by suanjiansalt** [comment]
bruh, misoperation

**Comment by RDIL** [comment]
> But I prefer to paste lines to github web to commit because I don't get familiar to the steps you commit in VSCode.

https://www.youtube.com/watch?v=B8RSMBSzFuA

**Review by RDIL — APPROVED** [review]
Looks good. As long as someone has tested the latest changes in-game, this is good to merge.

**Pull request merged**
