### PR TITLE
feat: season of drop challenge part 2

### PR DESCRIPTION
**Pull request by suanjiansalt**
## Scope

- Add 'Surgical Procedure' challenge.

## Test Plan

The challenge is good to go.

The strange order of feat challenges will be fixed soon.

## Checklist

-   [x] I have run Prettier to reformat any changed files
-   [x] I have verified my changes work

### CODE REVIEW

**Comment by TheKotti** [comment]
Did the challenge work? I made this exact change locally and while the challenge showed up in the game, it would not unlock.

**Comment by RDIL** [comment]
Just tried it and it worked for me 🤔

**Comment by suanjiansalt** [comment]
> Just tried it and it worked for me 🤔

Just tried again and it didn't work for me... 😵

**Comment by RDIL** [comment]
Rolled back pending further investigation

**Comment by AnthonyFuller** [comment]
Works fine on official, does not work on Peacock (just tested). You have to exit for it to pop on official, and the in-game counter for guards killed does not work.

**Comment by suanjiansalt** [comment]
The only attribution uncertain here is `$Value.ActorType`.

**Comment by suanjiansalt** [comment]
Ah shite

**Comment by grappigegovert** [comment]
> You have to exit for it to pop on official, and the in-game counter for guards killed does not work (although this is an official issue).

Oh god, is IO's statemachine parser on their server different from what's in the game?

**Comment by RDIL** [comment]
@grappigegovert it's the same, but there may be some type casting that happens on the C# side

**Comment by AnthonyFuller** [comment]
It's because they check if `1` is equal to `"1"` and the context listener is named incorrectly. Changing those fixes the challenge on Peacock and in-game. I don't think we should support `$eq: [1, "1"]` as this seems like a one-off. Pushing fixed challenge now.

**Pull request merged**
